#!/usr/bin/env python3
"""Derive everything that depends on the field list from gea/spec/poc-data.json.

That file is sheet 'POC Data' of the workbook: one entry per prop. The database
columns are written by hand in the Alembic revisions (tests/gea compares them
with the same file); everything else that repeats the field list is generated:

  gea_api/fields.py                        the props, their columns, types, steps and required flags
  spec/data-contract.schema.json           strict JSON Schema of the published contract
  api/openapi.yaml                         api/openapi.base.yaml + the run schemas
  frontend/src/api/generated.ts            TypeScript types of the API (openapi-typescript shape)
  frontend/src/api/fields.ts               the same field list for the Vue client
  spec/fields.md                           the workbook rows next to the columns that store them

Usage:  python gea/tools/generate.py [--check]
Requires PyYAML only.
"""
from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
GENERATED = "GENERATED by gea/tools/generate.py - do not edit by hand."
METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"]
# Workbook type (column D of 'POC Data') -> the kind the code works with.
KINDS = {"string": "string", "boolean": "boolean", "array<string>": "stringArray",
         "{start: date, end: date}": "dateRange", "array<{start: date, end: date}>": "dateRangeList"}
CONTROLS = {"text input", "select", "multiselect", "dateRange", "dateRangeList"}


def load_spec() -> dict:
    spec = json.loads((ROOT / "spec/poc-data.json").read_text(encoding="utf-8"))
    steps = [s["key"] for s in spec["steps"]]
    assert steps[0] == "main" and len(set(steps)) == len(steps), "steps: 'main' first, no duplicates"
    for form in ("createProject", "createRun"):
        props = [f["prop"] for f in spec[form]]
        assert len(set(props)) == len(props), f"{form}: duplicate prop"
        for field in spec[form]:
            assert field["type"] in KINDS and field["control"] in CONTROLS and field["step"] in steps, field
            assert sum(key in field for key in ("column", "columns", "table")) == 1, field
            if "requiredWhen" in field:
                assert not field["required"] and field["requiredWhen"]["prop"] in props, field
            if "defaultFrom" in field:
                assert field["defaultFrom"] in props, field
    order = [steps.index(f["step"]) for f in spec["createRun"]]
    assert order == sorted(order), "createRun: props are grouped by step, in step order"
    return spec


def run_config(spec: dict) -> list[dict]:
    """The createRun props after step 'main' (name, treaty): the run configuration."""
    return [f for f in spec["createRun"] if f["step"] != "main"]


def config_steps(spec: dict) -> list[tuple[int, dict, list[dict]]]:
    """(ordinal, step, fields) of the steps Snowflake executes; 'main' is the run identity."""
    return [(i, step, [f for f in spec["createRun"] if f["step"] == step["key"]])
            for i, step in enumerate(spec["steps"]) if step["key"] != "main"]


# ----------------------------------------------------------------------------- gea_api/fields.py
def python_fields(spec: dict) -> str:
    out = [f'"""{GENERATED}', "",
           "The props of workbook sheet 'POC Data' (gea/spec/poc-data.json): what they are called in the API,",
           "which column of gea.\"Project\" or gea.\"Run\" holds them, their type, wizard step and whether the",
           'workbook marks them as required."""', "from __future__ import annotations", "",
           "from dataclasses import dataclass", "", "",
           "@dataclass(frozen=True)", "class Field:",
           "    prop: str                      # name in the API and in the data contract (workbook column A)",
           "    display_name: str              # workbook column B",
           "    step: str                      # workbook column C",
           "    kind: str                      # string | boolean | stringArray | dateRange | dateRangeList",
           "    control: str                   # workbook column E",
           "    required: bool                 # workbook column F",
           "    columns: tuple[str, ...]       # columns of the table; a date range has two, a list of ranges none",
           "    table: str | None = None       # set when the values are rows of another table",
           "    required_when: tuple[str, object] | None = None   # (prop, value): required only then",
           "    default_from: str | None = None                   # prop whose value is the default",
           "    lookup: str | None = None      # lookup table that holds the allowed values", "", "",
           f"SPEC_VERSION = {json.dumps(spec['specVersion'])}", "",
           "# (key, title) of the wizard steps, in order. 'main' is the run identity (name, treaty).",
           "STEPS: tuple[tuple[str, str], ...] = ("]
    out += [f"    ({json.dumps(s['key'])}, {json.dumps(s['title'])})," for s in spec["steps"]]
    out += [")", "CONFIG_STEPS: tuple[str, ...] = tuple(key for key, _ in STEPS[1:])", ""]

    def field(f: dict) -> str:
        columns = tuple(f["columns"]) if "columns" in f else (f["column"],) if "column" in f else ()
        parts = [json.dumps(f["prop"]), json.dumps(f["displayName"]), json.dumps(f["step"]),
                 json.dumps(KINDS[f["type"]]), json.dumps(f["control"]), repr(f["required"]),
                 "(" + ", ".join(json.dumps(c) for c in columns) + ("," if len(columns) == 1 else "") + ")"]
        if "table" in f:
            parts.append(f"table={json.dumps(f['table'])}")
        if "requiredWhen" in f:
            parts.append(f"required_when=({json.dumps(f['requiredWhen']['prop'])}, {f['requiredWhen']['equals']!r})")
        if "defaultFrom" in f:
            parts.append(f"default_from={json.dumps(f['defaultFrom'])}")
        if "lookup" in f:
            parts.append(f"lookup={json.dumps(f['lookup'])}")
        return "    Field(" + ", ".join(parts) + "),"

    out += ["PROJECT_FIELDS: tuple[Field, ...] = ("] + [field(f) for f in spec["createProject"]] + [")", ""]
    out += ["RUN_FIELDS: tuple[Field, ...] = ("] + [field(f) for f in spec["createRun"]] + [")", "",
            "# The run configuration: every createRun prop after step 'main'.",
            "RUN_CONFIG: tuple[Field, ...] = tuple(f for f in RUN_FIELDS if f.step != \"main\")",
            "RUN_FIELD: dict[str, Field] = {f.prop: f for f in RUN_FIELDS}", ""]
    return "\n".join(out)


# ----------------------------------------------------------------------------- JSON Schema
DATE_RANGE = {"type": "object", "additionalProperties": False, "required": ["start", "end"],
              "properties": {"start": {"type": "string", "format": "date"},
                             "end": {"type": "string", "format": "date"}}}


def field_schema(field: dict, date_range_ref: str) -> dict:
    kind = KINDS[field["type"]]
    if kind == "string":
        schema = {"type": "string", "minLength": 1}
    elif kind == "boolean":
        schema = {"type": "boolean"}
    elif kind == "stringArray":
        schema = {"type": "array", "items": {"type": "string", "minLength": 1}, "uniqueItems": True}
    elif kind == "dateRange":
        schema = {"$ref": date_range_ref}
    else:
        schema = {"type": "array", "items": {"$ref": date_range_ref}}
    if "$ref" not in schema:
        schema["title"] = field["displayName"]
    return schema


def strict_step_config(fields: list[dict], date_range_ref: str) -> dict:
    schema = {"type": "object", "additionalProperties": False,
              "required": [f["prop"] for f in fields if f["required"]],
              "properties": {f["prop"]: field_schema(f, date_range_ref) for f in fields}}
    for f in fields:
        if KINDS[f["type"]] in {"stringArray", "dateRangeList"}:
            schema["properties"][f["prop"]]["minItems"] = 1        # an empty list is stored as "not set"
    conditionals = [{"if": {"required": [f["requiredWhen"]["prop"]],
                            "properties": {f["requiredWhen"]["prop"]: {"const": f["requiredWhen"]["equals"]}}},
                     "then": {"required": [f["prop"]]}}
                    for f in fields if "requiredWhen" in f]
    if conditionals:
        schema["allOf"] = conditionals
    return schema


def options_of(spec: dict, prop: str) -> list[str]:
    return [value for value, _ in next(f for f in spec["createProject"] if f["prop"] == prop)["options"]]


def contract_schema(spec: dict) -> dict:
    uuid = {"type": "string", "format": "uuid"}
    steps = [{"type": "object", "additionalProperties": False, "required": ["key", "ordinal", "config"],
              "properties": {"key": {"const": step["key"]}, "ordinal": {"const": ordinal},
                             "config": strict_step_config(fields, "#/$defs/DateRange")}}
             for ordinal, step, fields in config_steps(spec)]
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://gea.plre.example/schemas/data-contract/{spec['specVersion']}.json",
        "$comment": GENERATED,
        "title": "GEA run data contract",
        "description": "Immutable, versioned snapshot of one run configuration. Stored in PostgreSQL "
                       "(gea.\"DataContract\") and delivered unchanged to Snowflake, which executes `steps` in order. "
                       "The props are those of workbook sheet 'POC Data'.",
        "type": "object", "additionalProperties": False,
        "required": ["specVersion", "contractId", "version", "projectId", "runId",
                     "createdAt", "createdBy", "project", "run", "steps"],
        "properties": {
            "specVersion": {"const": spec["specVersion"]},
            "contractId": uuid,
            "version": {"type": "integer", "minimum": 1, "description": "Contract version within the run."},
            "projectId": uuid,
            "runId": uuid,
            "createdAt": {"type": "string", "format": "date-time"},
            "createdBy": {"type": "object", "additionalProperties": False, "required": ["id", "name"],
                          "properties": {"id": uuid, "name": {"type": "string"}}},
            "project": {"type": "object", "additionalProperties": False,
                        "required": ["name", "region", "businessPurpose", "benefit"],
                        "properties": {
                            "name": {"type": "string", "minLength": 1},
                            "region": {"enum": options_of(spec, "region")},
                            "businessPurpose": {"enum": options_of(spec, "businessPurpose")},
                            "benefit": {"type": "array", "minItems": 1, "uniqueItems": True,
                                         "items": {"enum": options_of(spec, "benefit")}}}},
            "run": {"type": "object", "additionalProperties": False, "required": ["name", "treaty"],
                    "properties": {"name": {"type": "string", "minLength": 1},
                                   "treaty": {"type": "string", "minLength": 1}}},
            "steps": {"type": "array", "prefixItems": steps, "items": False,
                      "minItems": len(steps), "maxItems": len(steps)},
        },
        "$defs": {"DateRange": DATE_RANGE},
    }


# ----------------------------------------------------------------------------- OpenAPI
def nullable(schema: dict) -> dict:
    """The same member where it may be null: an empty prop of a draft, or "remove" in a merge patch."""
    if "$ref" in schema:
        return {"oneOf": [schema, {"type": "null"}]}
    return {**schema, "type": [schema["type"], "null"]}


def openapi(base: dict, spec: dict) -> dict:
    """Add the schemas that repeat the field list, and wrap every 2xx body in the envelope."""
    api = copy.deepcopy(base)
    schemas = api["components"]["schemas"]
    config = run_config(spec)
    date_range = "#/components/schemas/DateRange"
    members = {}
    for f in config:
        schema = nullable(field_schema(f, date_range))
        note = f"createRun.{f['prop']}, step {f['step']}" + (", required to submit" if f["required"] else "")
        if "oneOf" in schema:
            schema["description"] = f"{f['displayName']} ({note})."
        else:
            schema["description"] = f"{note[0].upper() + note[1:]}."
        members[f["prop"]] = schema

    schemas["StepKey"] = {"type": "string", "enum": [s["key"] for s in spec["steps"]],
                          "description": "The steps of the run wizard (workbook column 'Section / Step'), in order."}
    schemas["ParameterName"] = {
        "type": "string", "enum": [f["prop"] for f in spec["createRun"]],
        "description": "A createRun field of workbook sheet 'POC Data'."}
    schemas["RunConfiguration"] = {
        "type": "object", "required": list(members),
        "description": "The configuration props of a run, one per createRun.* row of workbook sheet 'POC Data'. "
                       "Every prop is always present; a prop that is not filled in yet is null.",
        "properties": members}
    identity = {
        "name": {"type": "string", "minLength": 1, "maxLength": 200, "description": "createRun.name."},
        "treaty": {"type": "string", "minLength": 1, "description": "createRun.treaty."}}
    schemas["RunCreate"] = {
        "type": "object", "additionalProperties": False, "required": ["projectId", "name", "treaty"],
        "description": "createRun. Only the project, the name and the treaty are needed to start the draft; "
                       "any configuration prop may be sent with it.",
        "properties": {
            "projectId": {"type": "string", "format": "uuid", "description": "The project that receives the run."},
            **identity,
            "cloneSourceId": {"type": "string", "format": "uuid",
                              "description": "Run whose configuration is copied into the new draft (Run.CloneSourceId)."},
            **members}}
    schemas["RunPatch"] = {
        "type": "object", "additionalProperties": False, "minProperties": 1,
        "description": "JSON Merge Patch of a draft run: only the props that changed; null empties a prop. "
                       "name and treaty cannot be emptied.",
        "properties": {**identity, **members}}

    # The envelope: every 2xx body is {"data": <what the base file declares>, "error": null}.
    wrapped: set[int] = set()
    for item in api["paths"].values():
        for method, operation in item.items():
            if method not in METHODS:
                continue
            for status, response in operation["responses"].items():
                if not str(status).startswith("2") or id(response) in wrapped:
                    continue
                wrapped.add(id(response))
                media = response["content"]["application/json"]
                media["schema"] = {"type": "object", "required": ["data", "error"],
                                   "properties": {"data": media["schema"], "error": {"type": "null"}}}
    return api


class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True



def openapi_yaml(api: dict) -> str:
    body = yaml.dump(api, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=110)
    return (f"# {GENERATED}\n# Edit gea/api/openapi.base.yaml (routes and schemas) or\n"
            f"# gea/spec/poc-data.json (the props of sheet 'POC Data'), then run the generator.\n" + body)


# ----------------------------------------------------------------------------- TypeScript
# Emits the same module shape as `openapi-typescript` v7 (paths / components /
# operations), so `npm run generate:api` can overwrite this file with the real
# tool's output without touching client.ts, fields.ts or the composables.
IDENT = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def ts_key(name: str) -> str:
    return name if IDENT.match(name) else json.dumps(name)


def ts_ref(ref: str) -> str:
    _, _, section, name = ref.split("/")[:4]
    return f'components["{section}"]["{name}"]'


def ts_doc(schema: dict, pad: str) -> str:
    notes = []
    if isinstance(schema, dict):
        if "format" in schema:
            notes.append(f"Format: {schema['format']}")
        if schema.get("description"):
            notes.append("@description " + " ".join(str(schema["description"]).split()).replace("*/", "* /"))
    return f"{pad}/** {' | '.join(notes)} */\n" if notes else ""


def ts_type(schema, depth: int = 0) -> str:
    if schema is True or schema == {} or schema is None:
        return "unknown"
    if "$ref" in schema:
        return ts_ref(schema["$ref"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "oneOf" in schema or "anyOf" in schema:
        return " | ".join(ts_type(s, depth) for s in schema.get("oneOf") or schema["anyOf"])
    if "allOf" in schema:
        return " & ".join(ts_type(s, depth) for s in schema["allOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_type({**schema, "type": one}, depth) for one in kind)
    if kind == "null":
        return "null"
    if kind in ("integer", "number"):
        return "number"
    if kind in ("string", "boolean"):
        return kind
    if kind == "array":
        inner = ts_type(schema.get("items", {}), depth)
        return f"({inner})[]" if " " in inner and not inner.startswith("{") else f"{inner}[]"
    if kind == "object" or "properties" in schema:
        pad, close = "    " * (depth + 1), "    " * depth
        required = set(schema.get("required", []))
        lines = [f"{ts_doc(sub, pad)}{pad}{ts_key(name)}{'' if name in required else '?'}: {ts_type(sub, depth + 1)};"
                 for name, sub in schema.get("properties", {}).items()]
        if schema.get("additionalProperties") is True:
            lines.append(f"{pad}[key: string]: unknown;")
        return "{\n" + "\n".join(lines) + f"\n{close}}}" if lines else "Record<string, never>"
    return "unknown"


def ts_content(node: dict, depth: int) -> str:
    """`content` member of a request body or response."""
    pad = "    " * depth
    if not node.get("content"):
        return f"{pad}content?: never;"
    body = "\n".join(f'{pad}    {json.dumps(media)}: {ts_type(spec.get("schema", {}), depth + 1)};'
                     for media, spec in node["content"].items())
    return f"{pad}content: {{\n{body}\n{pad}}};"


def ts_response(node: dict, depth: int) -> str:
    if "$ref" in node:
        return ts_ref(node["$ref"])
    pad = "    " * depth
    headers = "".join(
        f"{pad}        {ts_key(name)}?: {ts_ref(h['$ref']) if '$ref' in h else ts_type(h.get('schema', {}), depth + 2)};\n"
        for name, h in node.get("headers", {}).items())
    return (f"{{\n{pad}    headers: {{\n{headers}{pad}        [name: string]: unknown;\n{pad}    }};\n"
            f"{ts_content(node, depth + 1)}\n{pad}}}")


def ts_parameters(spec: dict, params: list[dict], depth: int) -> str:
    pad = "    " * depth
    groups: dict[str, list[str]] = {"query": [], "header": [], "path": [], "cookie": []}
    required_group = {name: False for name in groups}
    for param in params:
        ref = param.get("$ref")
        resolved = spec["components"]["parameters"][ref.split("/")[-1]] if ref else param
        kind = ts_ref(ref) if ref else ts_type(resolved.get("schema", {}), depth + 2)
        required = resolved.get("required", False)
        required_group[resolved["in"]] |= required
        groups[resolved["in"]].append(
            f"{ts_doc(resolved, pad + '        ')}{pad}        {ts_key(resolved['name'])}{'' if required else '?'}: {kind};")
    lines = []
    for name, members in groups.items():
        if members:
            body = "\n".join(members)
            lines.append(f"{pad}    {name}{'' if required_group[name] else '?'}: {{\n{body}\n{pad}    }};")
        else:
            lines.append(f"{pad}    {name}?: never;")
    return "{\n" + "\n".join(lines) + f"\n{pad}}}"


def typescript(spec: dict) -> str:
    out = ["/**", f" * {GENERATED}",
           " * Same shape as `openapi-typescript` v7 output for gea/api/openapi.yaml.",
           " * `npm run generate:api` replaces this file with the output of the real tool.", " */", "",
           "export interface paths {"]
    operations: list[str] = []
    for path, item in spec["paths"].items():
        shared = item.get("parameters", [])
        out.append(f"    {json.dumps(path)}: {{")
        out.append(f"        parameters: {ts_parameters(spec, shared, 2)};")
        for method in METHODS:
            if method not in item:
                out.append(f"        {method}?: never;")
                continue
            op = item[method]
            out.append(f"        {method}: operations[{json.dumps(op['operationId'])}];")
            body = op.get("requestBody")
            request = "        requestBody?: never;" if not body else (
                f"        requestBody{'' if body.get('required') else '?'}: {{\n{ts_content(body, 3)}\n        }};")
            responses = "\n".join(f"            {status}: {ts_response(node, 3)};"
                                  for status, node in op["responses"].items())
            operations.append(f"    {ts_key(op['operationId'])}: {{\n"
                              f"        parameters: {ts_parameters(spec, shared + op.get('parameters', []), 2)};\n"
                              f"{request}\n        responses: {{\n{responses}\n        }};\n    }};")
        out.append("    };")
    out += ["}", "export type webhooks = Record<string, never>;", "export interface components {", "    schemas: {"]
    for name, schema in spec["components"]["schemas"].items():
        out.append(f"{ts_doc(schema, '        ')}        {ts_key(name)}: {ts_type(schema, 2)};")
    out += ["    };", "    responses: {"]
    for name, node in spec["components"]["responses"].items():
        out.append(f"{ts_doc(node, '        ')}        {ts_key(name)}: {ts_response(node, 2)};")
    out += ["    };", "    parameters: {"]
    for name, node in spec["components"]["parameters"].items():
        out.append(f"{ts_doc(node, '        ')}        {ts_key(name)}: {ts_type(node.get('schema', {}), 2)};")
    out += ["    };", "    requestBodies: never;", "    headers: {"]
    for name, node in spec["components"].get("headers", {}).items():
        out.append(f"{ts_doc(node, '        ')}        {ts_key(name)}: {ts_type(node.get('schema', {}), 2)};")
    out += ["    };", "    pathItems: never;", "}",
            "export type $defs = Record<string, never>;", "export interface operations {", *operations, "}", ""]
    return "\n".join(out)


def typescript_fields(spec: dict) -> str:
    config = run_config(spec)
    out = ["/**", f" * {GENERATED}",
           " * The props of workbook sheet 'POC Data' for the Vue client: steps, types, required flags.", " */",
           'import type { components } from "./generated";', "",
           'type Schemas = components["schemas"];', "",
           "/** The wizard steps in order; \"main\" is the run identity (name, treaty). */",
           "export const STEP_KEYS = [" + ", ".join(json.dumps(s["key"]) for s in spec["steps"])
           + '] as const satisfies readonly Schemas["StepKey"][];',
           "export type StepKey = (typeof STEP_KEYS)[number];", "",
           "export const STEP_TITLES: Record<StepKey, string> = {"]
    out += [f'    {s["key"]}: {json.dumps(s["title"])},' for s in spec["steps"]]
    out += ["};", "",
            "/** A prop of the run form: createRun.name, createRun.treaty and the configuration props. */",
            'export type RunProp = "name" | "treaty" | keyof Schemas["RunConfiguration"];', "",
            "export interface RunField {",
            "    prop: RunProp;",
            "    displayName: string;",
            "    step: StepKey;",
            '    kind: "string" | "boolean" | "stringArray" | "dateRange" | "dateRangeList";',
            '    control: "text input" | "select" | "multiselect" | "dateRange" | "dateRangeList";',
            "    required: boolean;",
            "}", "",
            "/** Every createRun prop, in workbook order. */",
            "export const RUN_FIELDS: readonly RunField[] = ["]
    for f in spec["createRun"]:
        out.append(f'    {{ prop: {json.dumps(f["prop"])}, displayName: {json.dumps(f["displayName"])}, '
                   f'step: {json.dumps(f["step"])}, kind: {json.dumps(KINDS[f["type"]])}, '
                   f'control: {json.dumps(f["control"])}, required: {json.dumps(f["required"])} }},')
    out += ["];", "",
            "/** The props of each step, for laying out the wizard. */",
            "export const STEP_FIELDS: Record<StepKey, readonly RunProp[]> = {"]
    for s in spec["steps"]:
        out.append(f'    {s["key"]}: [' + ", ".join(json.dumps(f["prop"]) for f in spec["createRun"]
                                                    if f["step"] == s["key"]) + "],")
    out += ["};", "",
            "/** Required props per step, for marking inputs; the API remains authoritative. */",
            "export const REQUIRED_FIELDS: Record<StepKey, readonly RunProp[]> = {"]
    for s in spec["steps"]:
        out.append(f'    {s["key"]}: [' + ", ".join(json.dumps(f["prop"]) for f in spec["createRun"]
                                                    if f["step"] == s["key"] and f["required"]) + "],")
    out += ["};", ""]
    assert len(config) + 2 == len(spec["createRun"])
    return "\n".join(out)


# ----------------------------------------------------------------------------- spec/fields.md
PG_TYPES = {"string": "text", "boolean": "boolean", "stringArray": "text[]", "dateRange": "date", "dateRangeList": "date"}


def fields_markdown(spec: dict) -> str:
    """The workbook rows next to the database columns that store them: one line per prop."""
    titles = {s["key"]: s["title"] for s in spec["steps"]}

    def stored(form: str, f: dict) -> str:
        table = {"createProject": "Project", "createRun": "Run"}[form]
        kind = PG_TYPES[KINDS[f["type"]]]
        if "table" in f:
            columns = {"ProjectBenefit": "BenefitId", "RunStudyPeriodExclusion": "StartDate`, `EndDate"}[f["table"]]
            return f'`{f["table"]}`.`{columns}` (one row per value)'
        names = f["columns"] if "columns" in f else [f["column"]]
        text = f'`{table}`.' + ", ".join(f"`{name}`" for name in names) + f" {kind}"
        return text + (f' -> `{f["lookup"]}`' if "lookup" in f else "")

    def required(f: dict) -> str:
        if "requiredWhen" in f:
            when = f["requiredWhen"]
            return f'when `{when["prop"]}` is {json.dumps(when["equals"])}'
        return "yes" if f["required"] else "no"

    out = ["# Workbook fields and where they are stored", "",
           f"<!-- {GENERATED} -->", "",
           f"Source: `{spec['source']}` (rows 5 to 40). One line per row of that sheet; Prop, Display name,",
           "Step, Type, Control and Required are the workbook's own columns. Every prop is a column of",
           'gea."Project" or gea."Run", or rows of a child table when it is a list of date ranges or a multiselect',
           "of a lookup. To change a field: edit `poc-data.json`, add an Alembic revision for the column and run",
           "`python gea/tools/generate.py`; `tests/gea/test_migration_sql.py` fails until the three agree.", ""]
    for form, heading in (("createProject", "Create project (`createProject.*`)"), ("createRun", "Create run (`createRun.*`)")):
        out += [f"## {heading}", "",
                "| Prop | Display name | Step | Type | Control | Required | Stored in |",
                "|---|---|---|---|---|---|---|"]
        for f in spec[form]:
            out.append(f'| `{f["prop"]}` | {f["displayName"]} | {titles[f["step"]]} | `{f["type"]}` | {f["control"]} '
                       f'| {required(f)} | {stored(form, f)} |')
        out.append("")
    return "\n".join(out)


# ----------------------------------------------------------------------------- main
def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when a generated file is out of date")
    args = parser.parse_args()

    spec = load_spec()
    outputs = {REPO / "gea_api/fields.py": python_fields(spec),
               ROOT / "spec/data-contract.schema.json": json.dumps(contract_schema(spec), indent=2) + "\n",
               ROOT / "spec/fields.md": fields_markdown(spec)}
    base_file = ROOT / "api/openapi.base.yaml"
    if base_file.exists():
        api = openapi(yaml.safe_load(base_file.read_text(encoding="utf-8")), spec)
        outputs[ROOT / "api/openapi.yaml"] = openapi_yaml(api)
        outputs[ROOT / "frontend/src/api/generated.ts"] = typescript(api)
        outputs[ROOT / "frontend/src/api/fields.ts"] = typescript_fields(spec)

    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path.relative_to(REPO))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if args.check and stale:
        print("Out of date: " + ", ".join(map(str, stale)), file=sys.stderr)
        return 1
    print(("Up to date" if not stale else "Wrote " + ", ".join(map(str, stale))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
