"""GENERATED by gea/tools/generate.py - do not edit by hand.

The props of workbook sheet 'POC Data' (gea/spec/poc-data.json): what they are called in the API,
which column of gea."Project" or gea."Run" holds them, their type, wizard step and whether the
workbook marks them as required."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Field:
    prop: str                      # name in the API and in the data contract (workbook column A)
    display_name: str              # workbook column B
    step: str                      # workbook column C
    kind: str                      # string | boolean | stringArray | dateRange | dateRangeList
    control: str                   # workbook column E
    required: bool                 # workbook column F
    columns: tuple[str, ...]       # columns of the table; a date range has two, a list of ranges none
    table: str | None = None       # set when the values are rows of another table
    required_when: tuple[str, object] | None = None   # (prop, value): required only then
    default_from: str | None = None                   # prop whose value is the default
    lookup: str | None = None      # lookup table that holds the allowed values


SPEC_VERSION = "1.0"

# (key, title) of the wizard steps, in order. 'main' is the run identity (name, treaty).
STEPS: tuple[tuple[str, str], ...] = (
    ("main", "Main"),
    ("dataAndSetUp", "Data and set up"),
    ("segmentation", "Segmentation"),
    ("actuals", "Actuals"),
    ("ibnr", "IBNR"),
    ("assigningExpected", "Assigning expected"),
    ("ultimateCalculation", "Ultimate calculation"),
    ("actualExpected", "Actual / Expected"),
)
CONFIG_STEPS: tuple[str, ...] = tuple(key for key, _ in STEPS[1:])

PROJECT_FIELDS: tuple[Field, ...] = (
    Field("name", "Project name", "main", "string", "text input", True, ("Name",)),
    Field("region", "Region", "main", "string", "select", True, ("RegionId",), lookup="Region"),
    Field("businessPurpose", "Business purpose", "main", "string", "select", True, ("BusinessPurposeId",), lookup="BusinessPurpose"),
    Field("benefit", "Benefit", "main", "stringArray", "multiselect", True, (), table="ProjectBenefit", lookup="Benefit"),
)

RUN_FIELDS: tuple[Field, ...] = (
    Field("name", "Run name", "main", "string", "text input", True, ("Name",)),
    Field("treaty", "Treaty", "main", "string", "select", True, ("Treaty",)),
    Field("dataScope", "Data Scope", "dataAndSetUp", "stringArray", "multiselect", True, ("DataScope",)),
    Field("studyPeriod", "Study Period", "dataAndSetUp", "dateRange", "dateRange", True, ("StudyPeriodStart", "StudyPeriodEnd")),
    Field("studyPeriodExclusions", "Study Period Exclusions", "dataAndSetUp", "dateRangeList", "dateRangeList", False, (), table="RunStudyPeriodExclusion"),
    Field("studyPeriodTreatyOverride", "Study Period Treaty Override", "dataAndSetUp", "boolean", "select", True, ("StudyPeriodTreatyOverride",)),
    Field("perTreatyEndDatesMapping", "Per Treaty End Dates Mapping", "dataAndSetUp", "string", "select", False, ("PerTreatyEndDatesMapping",), required_when=("studyPeriodTreatyOverride", True)),
    Field("investigation", "Investigation", "dataAndSetUp", "string", "select", True, ("Investigation",)),
    Field("exposureMethod", "Exposure Method", "segmentation", "string", "select", True, ("ExposureMethod",)),
    Field("initialExposureMethod", "Initial - Exposure Method", "segmentation", "string", "select", True, ("InitialExposureMethod",)),
    Field("exposureExclusion", "Exposure Exclusion", "segmentation", "stringArray", "multiselect", False, ("ExposureExclusion",)),
    Field("policyTenureSegmentation", "Policy Tenure Segmentation", "segmentation", "string", "select", False, ("PolicyTenureSegmentation",)),
    Field("calendarTenureSegmentation", "Calendar Tenure Segmentation", "segmentation", "string", "select", False, ("CalendarTenureSegmentation",)),
    Field("attainedAgeSegmentation", "Attained-Age Segmentation", "segmentation", "string", "select", False, ("AttainedAgeSegmentation",)),
    Field("partialClaimTreatment", "Partial Claim Treatment", "actuals", "string", "select", True, ("PartialClaimTreatment",)),
    Field("amountBasis", "Amount Basis", "actuals", "string", "select", True, ("AmountBasis",)),
    Field("claimBasis", "Claim Basis", "ibnr", "string", "select", True, ("ClaimBasis",)),
    Field("ibnrMethodology", "IBNR Methodology", "ibnr", "string", "select", True, ("IbnrMethodology",)),
    Field("derivationMethod", "Derivation Method", "ibnr", "string", "select", True, ("DerivationMethod",)),
    Field("ibnrStudyPeriod", "IBNR Study Period", "ibnr", "dateRange", "dateRange", True, ("IbnrStudyPeriodStart", "IbnrStudyPeriodEnd"), default_from="studyPeriod"),
    Field("developmentFrequency", "Development Frequency", "ibnr", "string", "select", True, ("DevelopmentFrequency",)),
    Field("upliftFrequency", "Uplift Frequency", "ibnr", "string", "select", True, ("UpliftFrequency",)),
    Field("eventMonthFilter", "Event Month Filter", "ibnr", "boolean", "select", False, ("EventMonthFilter",)),
    Field("reportingMonthFilter", "Reporting Month Filter", "ibnr", "boolean", "select", False, ("ReportingMonthFilter",)),
    Field("ibnrRbnsBasis", "IBNR / RBNS Basis", "ibnr", "string", "select", True, ("IbnrRbnsBasis",)),
    Field("tailStartPeriod", "Tail Start Period", "ibnr", "string", "select", False, ("TailStartPeriod",)),
    Field("comparisonBases", "Comparison Bases", "assigningExpected", "string", "select", False, ("ComparisonBases",)),
    Field("trendAssumptions", "Trend Assumptions", "assigningExpected", "string", "select", False, ("TrendAssumptions",)),
    Field("adjustment", "Adjustment", "ultimateCalculation", "string", "select", True, ("Adjustment",)),
    Field("ultimateRbnsBasis", "RBNS Basis", "ultimateCalculation", "string", "select", True, ("UltimateRbnsBasis",)),
    Field("outputFrequency", "Output Frequency", "actualExpected", "stringArray", "multiselect", True, ("OutputFrequency",)),
    Field("additionalOutputFields", "Additional Output Fields", "actualExpected", "stringArray", "multiselect", False, ("AdditionalOutputFields",)),
)

# The run configuration: every createRun prop after step 'main'.
RUN_CONFIG: tuple[Field, ...] = tuple(f for f in RUN_FIELDS if f.step != "main")
RUN_FIELD: dict[str, Field] = {f.prop: f for f in RUN_FIELDS}
