/**
 * GENERATED by gea/tools/generate.py - do not edit by hand.
 * The props of workbook sheet 'POC Data' for the Vue client: steps, types, required flags.
 */
import type { components } from "./generated";

type Schemas = components["schemas"];

/** The wizard steps in order; "main" is the run identity (name, treaty). */
export const STEP_KEYS = ["main", "dataAndSetUp", "segmentation", "actuals", "ibnr", "assigningExpected", "ultimateCalculation", "actualExpected"] as const satisfies readonly Schemas["StepKey"][];
export type StepKey = (typeof STEP_KEYS)[number];

export const STEP_TITLES: Record<StepKey, string> = {
    main: "Main",
    dataAndSetUp: "Data and set up",
    segmentation: "Segmentation",
    actuals: "Actuals",
    ibnr: "IBNR",
    assigningExpected: "Assigning expected",
    ultimateCalculation: "Ultimate calculation",
    actualExpected: "Actual / Expected",
};

/** A prop of the run form: createRun.name, createRun.treaty and the configuration props. */
export type RunProp = "name" | "treaty" | keyof Schemas["RunConfiguration"];

export interface RunField {
    prop: RunProp;
    displayName: string;
    step: StepKey;
    kind: "string" | "boolean" | "stringArray" | "dateRange" | "dateRangeList";
    control: "text input" | "select" | "multiselect" | "dateRange" | "dateRangeList";
    required: boolean;
}

/** Every createRun prop, in workbook order. */
export const RUN_FIELDS: readonly RunField[] = [
    { prop: "name", displayName: "Run name", step: "main", kind: "string", control: "text input", required: true },
    { prop: "treaty", displayName: "Treaty", step: "main", kind: "string", control: "select", required: true },
    { prop: "dataScope", displayName: "Data Scope", step: "dataAndSetUp", kind: "stringArray", control: "multiselect", required: true },
    { prop: "studyPeriod", displayName: "Study Period", step: "dataAndSetUp", kind: "dateRange", control: "dateRange", required: true },
    { prop: "studyPeriodExclusions", displayName: "Study Period Exclusions", step: "dataAndSetUp", kind: "dateRangeList", control: "dateRangeList", required: false },
    { prop: "studyPeriodTreatyOverride", displayName: "Study Period Treaty Override", step: "dataAndSetUp", kind: "boolean", control: "select", required: true },
    { prop: "perTreatyEndDatesMapping", displayName: "Per Treaty End Dates Mapping", step: "dataAndSetUp", kind: "string", control: "select", required: false },
    { prop: "investigation", displayName: "Investigation", step: "dataAndSetUp", kind: "string", control: "select", required: true },
    { prop: "exposureMethod", displayName: "Exposure Method", step: "segmentation", kind: "string", control: "select", required: true },
    { prop: "initialExposureMethod", displayName: "Initial - Exposure Method", step: "segmentation", kind: "string", control: "select", required: true },
    { prop: "exposureExclusion", displayName: "Exposure Exclusion", step: "segmentation", kind: "stringArray", control: "multiselect", required: false },
    { prop: "policyTenureSegmentation", displayName: "Policy Tenure Segmentation", step: "segmentation", kind: "string", control: "select", required: false },
    { prop: "calendarTenureSegmentation", displayName: "Calendar Tenure Segmentation", step: "segmentation", kind: "string", control: "select", required: false },
    { prop: "attainedAgeSegmentation", displayName: "Attained-Age Segmentation", step: "segmentation", kind: "string", control: "select", required: false },
    { prop: "partialClaimTreatment", displayName: "Partial Claim Treatment", step: "actuals", kind: "string", control: "select", required: true },
    { prop: "amountBasis", displayName: "Amount Basis", step: "actuals", kind: "string", control: "select", required: true },
    { prop: "claimBasis", displayName: "Claim Basis", step: "ibnr", kind: "string", control: "select", required: true },
    { prop: "ibnrMethodology", displayName: "IBNR Methodology", step: "ibnr", kind: "string", control: "select", required: true },
    { prop: "derivationMethod", displayName: "Derivation Method", step: "ibnr", kind: "string", control: "select", required: true },
    { prop: "ibnrStudyPeriod", displayName: "IBNR Study Period", step: "ibnr", kind: "dateRange", control: "dateRange", required: true },
    { prop: "developmentFrequency", displayName: "Development Frequency", step: "ibnr", kind: "string", control: "select", required: true },
    { prop: "upliftFrequency", displayName: "Uplift Frequency", step: "ibnr", kind: "string", control: "select", required: true },
    { prop: "eventMonthFilter", displayName: "Event Month Filter", step: "ibnr", kind: "boolean", control: "select", required: false },
    { prop: "reportingMonthFilter", displayName: "Reporting Month Filter", step: "ibnr", kind: "boolean", control: "select", required: false },
    { prop: "ibnrRbnsBasis", displayName: "IBNR / RBNS Basis", step: "ibnr", kind: "string", control: "select", required: true },
    { prop: "tailStartPeriod", displayName: "Tail Start Period", step: "ibnr", kind: "string", control: "select", required: false },
    { prop: "comparisonBases", displayName: "Comparison Bases", step: "assigningExpected", kind: "string", control: "select", required: false },
    { prop: "trendAssumptions", displayName: "Trend Assumptions", step: "assigningExpected", kind: "string", control: "select", required: false },
    { prop: "adjustment", displayName: "Adjustment", step: "ultimateCalculation", kind: "string", control: "select", required: true },
    { prop: "ultimateRbnsBasis", displayName: "RBNS Basis", step: "ultimateCalculation", kind: "string", control: "select", required: true },
    { prop: "outputFrequency", displayName: "Output Frequency", step: "actualExpected", kind: "stringArray", control: "multiselect", required: true },
    { prop: "additionalOutputFields", displayName: "Additional Output Fields", step: "actualExpected", kind: "stringArray", control: "multiselect", required: false },
];

/** The props of each step, for laying out the wizard. */
export const STEP_FIELDS: Record<StepKey, readonly RunProp[]> = {
    main: ["name", "treaty"],
    dataAndSetUp: ["dataScope", "studyPeriod", "studyPeriodExclusions", "studyPeriodTreatyOverride", "perTreatyEndDatesMapping", "investigation"],
    segmentation: ["exposureMethod", "initialExposureMethod", "exposureExclusion", "policyTenureSegmentation", "calendarTenureSegmentation", "attainedAgeSegmentation"],
    actuals: ["partialClaimTreatment", "amountBasis"],
    ibnr: ["claimBasis", "ibnrMethodology", "derivationMethod", "ibnrStudyPeriod", "developmentFrequency", "upliftFrequency", "eventMonthFilter", "reportingMonthFilter", "ibnrRbnsBasis", "tailStartPeriod"],
    assigningExpected: ["comparisonBases", "trendAssumptions"],
    ultimateCalculation: ["adjustment", "ultimateRbnsBasis"],
    actualExpected: ["outputFrequency", "additionalOutputFields"],
};

/** Required props per step, for marking inputs; the API remains authoritative. */
export const REQUIRED_FIELDS: Record<StepKey, readonly RunProp[]> = {
    main: ["name", "treaty"],
    dataAndSetUp: ["dataScope", "studyPeriod", "studyPeriodTreatyOverride", "investigation"],
    segmentation: ["exposureMethod", "initialExposureMethod"],
    actuals: ["partialClaimTreatment", "amountBasis"],
    ibnr: ["claimBasis", "ibnrMethodology", "derivationMethod", "ibnrStudyPeriod", "developmentFrequency", "upliftFrequency", "ibnrRbnsBasis"],
    assigningExpected: [],
    ultimateCalculation: ["adjustment", "ultimateRbnsBasis"],
    actualExpected: ["outputFrequency"],
};
